- name: Install curl
  become: true
  apt:
    name: curl
    state: latest

- name: Clone repository
  ansible.builtin.git:
    repo: https://github.com/spring-petclinic/spring-petclinic-angular.git
    dest: /home/{{ username }}/spring-petclinic-angular/
    force: yes

- name: Update config
  ansible.builtin.script:
    cmd: set-params.sh {{_backend_ip}} {{_backend_port}}
    chdir: /home/{{ username }}/spring-petclinic-angular/

- name: Copy build script
  ansible.builtin.copy:
    src: build.sh
    dest: /home/{{ username }}/build.sh

- name: Add execute privileges
  become: true
  ansible.builtin.command:
    cmd: chmod +x ./build.sh
    chdir: /home/{{ username }}/

- name: Install package manager and deploy
  async: 3600
  poll: 0
  ansible.builtin.command:
    cmd: ./build.sh {{ _frontend_port }}
    chdir: /home/{{ username }}/
  become: yes
  become_method: sudo
  become_user: root
