- name: front - Copy script
  ansible.builtin.copy:
    src: run-front.sh
    dest: /home/{{username}}/run-front.sh

- name: front - Give permission
  ansible.builtin.command:
    cmd: chmod +x ./run-front.sh
    chdir: /home/{{username}}/

- name: front - Execute script 
  async: 3600
  poll: 0
  ansible.builtin.shell:
    cmd: ./run-front.sh {{backend_ip}} {{backend_port}} {{frontend_port}}
    chdir: /home/{{username}}/
