- name: backend - Copy run script BE
  ansible.builtin.copy:
    src: run-back.sh
    dest: /home/{{username}}/run-back.sh

- name: backend - Give access permission to run script 
  ansible.builtin.command:
    cmd: chmod +x ./run-back.sh
    chdir: /home/{{username}}/

- name: backend - Execute script 
  ansible.builtin.script:
    cmd: ./run-back.sh {{db_private_ip}} {{db_port}} {{backend_port}} {{folder}}
    chdir: /home/{{username}}/
