all:
  hosts:
    frontend_host:
      vm_name: "angular"
      ansible_user: "azureuser"
      ansible_password: "{{ ansible_password }}"
      ansible_host: "{{ frontend_ip }}"
      ansible_python_interpreter: /usr/bin/python3

    backend_host:
      vm_name: "spring"
      ansible_user: "azureuser"
      ansible_password: "{{ ansible_password }}"
      ansible_host: "{{ backend_ip }}"
      ansible_python_interpreter: /usr/bin/python3

    db_host:
      vm_name: "db"
      ansible_user: "azureuser"
      ansible_password: "{{ ansible_password }}"
      ansible_host: "{{ db_ip }}"
      ansible_python_interpreter: /usr/bin/python3

  children:
    frontend:
      hosts:
        frontend_host:
          backend_private_ip: "{{ backend_ip }}"
          backend_port: "{{ backend_port }}"
          frontend_port: "{{ frontend_port }}"
    backend:
      hosts:
        backend_host:
          backend_port: "{{ backend_port }}"
          db_private_ip: "{{ db_ip }}"
          db_port: "{{ db_port }}"
          folder: "back_folder"
    database:
      hosts:
        db_host:
          db_port: "{{ db_port }}"
