all:
  hosts:
    frontend_host:
      vm_name: "angular"
      ansible_user: "azureuser"
      ansible_password: "Haslo123Haslo123"
      ansible_host: "20.215.244.254"

    backend_host:
      vm_name: "spring"
      ansible_user: "azureuser"
      ansible_password: "Haslo123Haslo123"
      ansible_host: "20.215.244.208"

    db_host:
      vm_name: "db"
      ansible_user: "azureuser"
      ansible_password: "Haslo123Haslo123"
      ansible_host: "20.215.244.140"

  children:
    frontend:
      hosts:
        frontend_host:
          backend_private_ip: "20.215.244.208"
          backend_port: 9966
          frontend_port: 4200
    backend:
      hosts:
        backend_host:
          backend_port: 9966
          db_private_ip: "20.215.244.140"
          db_port: 3306
    database:
      hosts:
        db_host:
          db_port: 3306
