- name: db-master - Copy script
  ansible.builtin.copy:
    src: db-master.sh
    dest: /home/{{username}}/db-master.sh

- name: db-master - Give permission
  ansible.builtin.command:
    cmd: chmod +x ./db-master.sh
    chdir: /home/{{username}}/

- name: db-master - Execute script 
  ansible.builtin.script:
    cmd: ./db-master.sh {{database_port}} {{database_user}} {{database_password}}
    chdir: /home/{{username}}/
