---
- name: Create Azure VMs
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Crate virtual network:
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefix: "{{ network_addr_prefix }}"

    - name: Add subnets
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        virtual_network_name: "{{ vnet_name }}"
        address_prefix: "{{ subnet_prefix }}"

    - import_tasks_from: create_vm.yml
      vars:
        vm_name: "{{db_vm_name}}"
        vm_size: "{{db_vm_size}}"
        vm_port: "{{db_port}}"
        vm_private_ip: "{{db_private_ip}}"

    - import_tasks_from: create_vm.yml
      vars:
        vm_name: "{{frontend_vm_name}}"
        vm_size: "{{frontend_vm_size}}"
        vm_port: "{{frontend_port}}"
        vm_private_ip: "{{frontend_private_ip}}"

    - import_tasks_from: create_vm.yml
      vars:
        vm_name: "{{backend_vm_name}}"
        vm_size: "{{backend_vm_size}}"
        vm_port: "{{backend_port}}"
        vm_private_ip: "{{backend_private_ip}}"

    # tasks for deallocate and poweroff resource group
    
