---
- name: Database install
  hosts: ansible_client
  retmote_user: root
  become: true
  tasks:
    - name: update system
      apt:
        name: update

    - name: install mysql-server
      apt:
        name: mysql-server

    - name: download Database init file
      get_url:
        url: https://raw.githubusercontent.com/spring-petclinic/spring-petclinic-rest/master/src/main/resources/db/mysql/initDB.sql

    - name: download Database populate file
      get_url:
        url: https://raw.githubusercontent.com/spring-petclinic/spring-petclinic-rest/master/src/main/resources/db/mysql/populateDB.sql