---
- name: Deploy application
  hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Print host info
      debug:
        msg: "Deploying to host {{ inventory_hostname }} with IP {{ ansible_host }}."

- name: Deploy database
  hosts: database
  become: true
  vars_files:
    - vars.yml
  roles:
    - database

- name: Deploy backend
  hosts: backend
  become: true
  vars_files:
    - vars.yml
  roles:
    - backend

- name: Deploy frontend
  hosts: frontend
  become: true
  vars_files:
    - vars.yml
  roles:
    - frontend
