- name: db - Copy script
  ansible.builtin.copy:
    src: db.sh
    dest: /home/azureuser/db.sh

- name: db - Give permission 
  ansible.builtin.command:
    cmd: chmod +x ./db.sh
    chdir: /home/azureuser/

- name: db - Execute script 
  ansible.builtin.script:
    cmd: ./db.sh
    chdir: /home/azureuser/
